### ISSUE TITLE
Missing php5-mysql package.

### ISSUE THREAD

**Issue by NoKriK** [scaleway/image-app-lemp#10]
We're providing a pre-install MySQL on an LEMP image but the php5-mysql package is not installed.
This solves the issue:
```
apt-get install php5-mysql
```

Should be added to the Dockerfile.

**Comment by moul** [comment]
`php5-mysql` is missing, but `pdo_mysql` is installed, isn't it enough for php applications ?

**Comment by NoKriK** [comment]
Where is it installed?
As far as I understand, [this](https://github.com/scaleway/image-app-lemp/blob/master/Dockerfile#L37) only enables the module if it's already installed.
What I understand is that ```pdo_mysql``` is installed by ```php5-mysql```.

The PHP application I tried to install (roundcube) complained that ```pdo_mysql``` was missing.

**Comment by moul** [comment]
You're probably right, @aimxhaisse can you check ?

**Comment by moul** [comment]
Also, do net hesitate to install other packages matching `php{,5}-*` but do not load them all, just in case some of them are bad for performances
