### ISSUE TITLE
Default configuration triggers a 500 when file does not exist

### ISSUE THREAD

**Issue by NoKriK** [scaleway/image-app-lemp#9]
Accessing a non existent file triggers an error with the following error in the logs:
```
2015/08/07 22:43:56 [error] 1723#0: *22 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: XX.XX.XX.XXX, server: your.domain.com, request: "GET /roundbla HTTP/1.1", host: "212.47.229.230"
```

**Comment by NoKriK** [comment]
This is simply related to this configuration part:
```
       location / {
                try_files $uri $uri/ /index.html;
       }
```

index.html does not exist by default.

**Comment by moul** [comment]
we should create a default `index.html` file and provide instructions about getting started with the image (or at least a link to the documentation)
